//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalSN_App
{
    using System;
    using System.Collections.Generic;
    using System.Windows;

    public partial class Врач
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Врач()
        {
            this.ДанныеДляВхода = new HashSet<ДанныеДляВхода>();
            this.Пациент = new HashSet<Пациент>();
            this.УчетПриема = new HashSet<УчетПриема>();
        }
    
        public int idВрача { get; set; }
        public string ФИО { get; set; }
        public string Адрес { get; set; }
        public Nullable<System.DateTime> ДатаРождения { get; set; }
        public Nullable<int> Телефон { get; set; }
        public string ВремяРаботы { get; set; }
        public Nullable<int> idРоли { get; set; }
        public Nullable<int> idДолжности { get; set; }
        public Nullable<bool> Статус { get; set; }
        public string СтатусВрача
        {
            get
            {
                return (bool)Статус ? "Работает" : "Уволен";
            }
            set
            {
                if (value == "Работает" || value == "Уволен")
                {
                    Статус = value == "Работает";
                }
                else
                {
                    MessageBox.Show("Только Работает/Уволен!", "Ошибка изменения!", MessageBoxButton.OK, MessageBoxImage.Error);
                }
            }
        }

        public virtual Должность Должность { get; set; }
        public virtual Роль Роль { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ДанныеДляВхода> ДанныеДляВхода { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Пациент> Пациент { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<УчетПриема> УчетПриема { get; set; }
    }
}
