//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalSN_App
{
    using System;
    using System.Collections.Generic;
    
    public partial class ДанныеДляВхода
    {
        public string Логин { get; set; }
        public string Пароль { get; set; }
        public Nullable<int> idВрача { get; set; }
    
        public virtual Врач Врач { get; set; }
    }
}
