//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalSN_App
{
    using System;
    using System.Collections.Generic;
    using System.Windows;

    public partial class УчетПриема
    {
        public int Номер { get; set; }
        public Nullable<int> idПациента { get; set; }
        public Nullable<int> idВрача { get; set; }
        public Nullable<System.DateTime> ДатаПриема { get; set; }
        public Nullable<bool> Присутствие { get; set; }
    
        public string Пришествие
        {
            get
            {
                return (bool)Присутствие ? "Да" : "Нет";
            }
            set
            {
                if(value == "Да" || value == "Нет")
                {
                    Присутствие = value == "Да";
                }
                else
                {
                    MessageBox.Show("Только Да/Нет!", "Ошибка изменения!", MessageBoxButton.OK, MessageBoxImage.Error);
                }
            }
        }
        public virtual Врач Врач { get; set; }
        public virtual Пациент Пациент { get; set; }
    }
}
